### ISSUE TITLE
Unused 'groups' parameter for user

### ISSUE THREAD

**Issue by sedunne** [deric/puppet-accounts#51] opened 2016-08-10 16:22 UTC
I've noticed that the `groups` parameter for the `accounts::user` resource is defined, but never is actually used.  I was having an issue where users weren't being added to the groups that I defined them under.  Adding the `groups` attribute to the `user` resource in `accounts::user` seems to fix that behavior.

I'm curious if there is a reason for this, or if it perhaps was just an oversight or something.  I'm not specifying group membership at the group level (as I'd rather just tell the users which groups they should go to), so perhaps this is why I'm having difficulties, but any insight is appreciated!

**Comment by deric** [comment] 2016-08-10 16:59
Which version do you use? Could you provide a snippet of configuration, so that I can try to replicate it?

**Comment by sedunne** [comment] 2016-08-10 19:06
Sure thing (this may be a slightly unusual configuration, but I don't see why it shouldn't work).  This can be tested in vagrant w/puppet apply (stdlib is required for the loadyaml() call):

manifest.pp:
```
node default {

  ## is same format as hiera, just stored as separate yaml file
  $users = loadyaml('/vagrant/yaml/users.yaml')

  ## "workaround" for primary groups not being created
  $user_primary_groups = {}
  $users.each |$usr, $opts| {
    $tmp = { 'ensure' => present, }
    inline_template("<% @user_primary_groups[\"${usr}\"] = @tmp -%>")
  }
  create_resources( ::accounts::group, $user_primary_groups )
  ## end "workaround"

  ## create a few groups
  $groups = ['groupa', 'groupb']
  ::accounts::group { $groups:
    ensure => present,
  }

  ## create users from loaded yaml 
  create_resources( ::accounts::user, $users )

}
```

users.yaml:
```
foo:
  ensure: 'present'
  groups: ['groupa']
```

(I'm also getting the issue reported in #50 where the primary group doesn't get created, thus the above workaround)

Using either the version in Forge (tagged 1.3.3), or the current master from GitHub, the groups will be created, the user (and its group) created, but the user isn't actually assigned to the group(s) specified in hiera/yaml.  If I add the `groups` param to the user resource (like [so](https://github.com/sedunne/puppet-accounts/commit/526686274512cf69127c82ec0f77b3167e6b0b8d)), then the user gets added to groups specified.

Let me know if I can answer/help with anything else.

**Comment by deric** [comment] 2016-10-10 14:11
The code you use a workaround:
```puppet
  $user_primary_groups = {}
  $users.each |$usr, $opts| {
    $tmp = { 'ensure' => present, }
    inline_template("<% @user_primary_groups[\"${usr}\"] = @tmp -%>")
  }
  create_resources( ::accounts::group, $user_primary_groups )
```
is pretty much the same [initialization of the primary groups in here](https://github.com/deric/puppet-accounts/blob/master/manifests/init.pp#L25), except the primary groups are extracted using a[ ruby function](https://github.com/deric/puppet-accounts/blob/master/lib/puppet/parser/functions/accounts_primary_groups.rb#L16). The function assigns groups membership "on the fly" which relationship dependencies which are otherwise difficult to handle.

So, using:
```puppet
class {'accounts': }
```
and yaml:
```yaml
accounts::users:
  foo:
    groups: ['groupa']
```
should have the same effect.

**Comment by philippdieter** [comment] 2016-11-11 18:50
I experience the same problem, users dont get assigned to groups. I use foreman and everything else works just fine.

# hash
pd:
  groups:
  - sudo

# puppet -V
4.7.0

# cat /etc/debian_version 
8.6

mod 'deric-accounts', '1.4.1'

Doesn't matter if I add the user to the group or the other way round. My knowledge in ruby is quite limited but it would be nice if we could solve this as this is a great module.

**Comment by hyperized** [comment] 2016-11-12 22:32
Same issue here. I have both groups and users assigned, but they do not get applied when defined purely in YAML format.

```
# site/profile/manifests/base.pp
class profile::base {
  class {'::accounts': }
}

# hieradata/common.yaml
classes:
 - 'profile::base'

accounts::user_defaults:
  purge_ssh_keys: true

accounts::groups:
  sudo:
    members: [ 'deploy']

accounts::users:
  deploy:
    comment: "Deployment user"
    groups: ['sudo']

# cat /etc/issue.net
Ubuntu 14.04.5 LTS

# /opt/puppetlabs/bin/puppet -V
4.8.0

# Puppetfile
mod 'deric-accounts', '1.4.1'
```

If I follow the documentation this _should_ work, but it doesn't.

It does not matter whether accounts::groups: is assigned prior or after .. or present at all.

**Comment by deric** [comment] 2016-11-16 09:27
@philippdieter @hyperized Which Ruby version do you use?

I'm sorry, I wasn't able to reproduce the issue. Any attempt to fix it would be just a desperate effort. I've tried to write [an acceptance test](https://github.com/deric/puppet-accounts/tree/master/spec/acceptance) but with the latest versions of development dependencies I'm unable to execute [any of them](https://travis-ci.org/deric/puppet-accounts/jobs/171343069) (tested on Debian 8 , Ubuntu 14.04, CentOS 7). It might be Docker/Puppet/Beaker/Hiera issue. I really don't know. If you could help me with this, we might be able to fix this issue.

**Comment by deric** [comment] 2016-11-16 09:54
@hyperized everything seems to be fine when accounts are included as puppet code (`puppet apply -e "class {'::accounts': }"`), is that right?

```
cat <<EOF > /etc/puppet/hiera.yaml
> ---
> :backends:
>   - yaml
> :hierarchy:
>   - "nodes/%{::trusted.certname}"
>   - common
> 
> :yaml:
>   :datadir: /etc/puppet/hieradata
> EOF
root@debian-8-x64:/# mkdir /etc/puppet/hieradata
root@debian-8-x64:/# cat <<EOF > /etc/puppet/hieradata/common.yaml                                                            
> accounts::user_defaults:
>   purge_ssh_keys: true
> 
> accounts::groups:
>   sudo:
>     members: [ 'deploy']
> 
> accounts::users:
>   deploy:
>     comment: "Deployment user"
>     groups: ['sudo']
> EOF
root@debian-8-x64:/# puppet apply -e "class {'::accounts': }"                                                                 
Notice: Compiled catalog for debian-8-x64 in environment production in 0.35 seconds
Notice: /Stage[main]/Accounts/Accounts::Group[deploy]/Group[deploy]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deploy]/User[deploy]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deploy]/Accounts::Authorized_keys[deploy]/File[/home/deploy/.ssh]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deploy]/Accounts::Authorized_keys[deploy]/File[/home/deploy/.ssh/authorized_keys]/ensure: created
Notice: /Stage[main]/Accounts::Groups/Accounts::Group[sudo]/Group[sudo]/members: members changed '' to 'deploy,deploy'
Notice: Finished catalog run in 0.23 seconds
```

```
root@debian-8-x64:/# id deploy  
uid=1001(deploy) gid=1001(deploy) groups=1001(deploy),27(sudo)
```

**Comment by deric** [comment] 2016-11-16 10:28
@hyperized as the [documentation suggest](https://docs.puppet.com/hiera/3.2/complete_example.html#using-hierainclude) you should use `hiera_include('classes')`:

```
$ puppet apply -e "hiera_include('classes')"                                      
Warning: Scope(Class[main]): Could not look up qualified variable '::trusted.certname'; 
Notice: Compiled catalog for debian-8-x64 in environment production in 0.38 seconds
Notice: /Stage[main]/Accounts/Accounts::Group[deploy]/Group[deploy]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deploy]/User[deploy]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deploy]/Accounts::Authorized_keys[deploy]/File[/home/deploy/.ssh]/ensure: created
Notice: /Stage[main]/Accounts::Users/Accounts::User[deploy]/Accounts::Authorized_keys[deploy]/File[/home/deploy/.ssh/authorized_keys]/ensure: created
Notice: /Stage[main]/Accounts::Groups/Accounts::Group[sudo]/Group[sudo]/members: members changed '' to 'deploy,deploy'
Notice: Finished catalog run in 0.23 seconds
```

**Comment by deric** [comment] 2016-11-18 08:02
I'm closing the issue as it become more a discussion than tracking an issue. If you run into any problems like make sure to upgrade to latest release and open a new issue with relevant information.

**Closed by deric** 2016-11-18 08:02 UTC
Labels: question
